name: satCheck
channels:
   - defaults
dependencies:
   # Core requirements
   - python=3.8
   - pip
   # Other packages
   - pandas
   - numpy
   - ephem
   - requests
   - astropy
   - matplotlib
   # Allow Jupyter Kernel to be created
   - ipykernel
   # Install some other dependecies
   - pip:
     - blimpy==2.0.11
     - git+https://github.com/UCBerkeleySETI/turbo_seti
     - pymysql
     - google-cloud-bigquery[bqstorage,pandas]
